from dotenv import load_dotenv

load_dotenv()

from datetime import datetime  # For created_at field
from typing import Optional, List, Dict, Any

from pydantic import BaseModel, Field, HttpUrl, model_validator


class UserBriefSchema(BaseModel):
    """
    Schema for the user's initial brief to generate an email template.
    """

    subject: str = Field(
        ..., min_length=1, description="The subject line of the email."
    )
    body_copy: str = Field(
        ..., min_length=1, description="The main body content/brief for the email."
    )
    image_suggestions: Optional[list[str]] = Field(
        default_factory=list,
        description="Optional list of suggestions or prompts for images.",
    )
    cta_text: Optional[str] = Field(
        default=None, description="Call to action button text."
    )
    cta_url: Optional[HttpUrl] = Field(default=None, description="Call to action URL.")
    # Add other fields as per the full brief definition if needed, e.g., brand_guidelines
    # brand_guidelines: Optional[str] = Field(default=None, description="Brand guidelines or specific instructions.")


class TemplateCreationRequest(BaseModel):
    """
    The request model for POST /templates endpoint.
    Wraps the user brief and any other client-side info.
    Supports both legacy (structured brief) and RAG (plain text) flows.
    """

    # --- Flow Control ---
    rag_flow: bool = Field(
        default=False,
        description="If true, initiates the RAG-based workflow with a plain text brief. If false, uses the legacy workflow with a structured user_brief.",
    )

    # --- Brief Inputs (conditionally required) ---
    user_brief: Optional[UserBriefSchema] = Field(
        default=None, description="The structured brief for the legacy generation flow."
    )
    plain_text_brief: Optional[str] = Field(
        default=None, description="The unstructured, plain text brief for the RAG flow."
    )

    # --- RAG Flow Options (Sprint 5) ---
    use_placeholders: bool = Field(
        default=True,
        description="If true, use the template with placeholder images. If false, use original media.",
    )

    # --- Other ---
    client_id: Optional[str] = Field(
        default=None, description="Optional client identifier."
    )  # As per plan_langgraph.md

    @model_validator(mode="after")
    def check_brief_based_on_flow(self) -> "TemplateCreationRequest":
        """Ensures that the correct brief type is provided based on the rag_flow flag."""
        is_rag = self.rag_flow
        has_plain_brief = self.plain_text_brief is not None
        has_user_brief = self.user_brief is not None

        if is_rag and not has_plain_brief:
            raise ValueError(
                "When rag_flow is true, 'plain_text_brief' must be provided."
            )
        if not is_rag and not has_user_brief:
            raise ValueError("When rag_flow is false, 'user_brief' must be provided.")
        if is_rag and has_user_brief:
            raise ValueError(
                "Ambiguous request: When rag_flow is true, only 'plain_text_brief' should be provided."
            )
        if not is_rag and has_plain_brief:
            raise ValueError(
                "Ambiguous request: When rag_flow is false, only 'user_brief' should be provided."
            )
        return self


class TemplateCreationResponseSchema(BaseModel):
    """
    Schema for the response after initiating template creation.
    """

    template_id: str = Field(
        description="Unique identifier for the template generation task (e.g., graph execution ID)."
    )
    task_id: str = Field(
        description="Can be the same as template_id, representing the graph execution ID."
    )
    status: str = Field(description="Initial status of the template creation process.")
    message: str = Field(description="A message confirming initiation.")
    status_poll_url: str = Field(description="URL to poll for status updates.")


# Example of how a status response schema might look (for GET /templates/{template_id}/status)
# This will be expanded significantly later.
class TemplateStatusSchema(BaseModel):
    template_id: str
    task_id: str
    status: str
    current_version_id: Optional[str] = None
    html_preview_url: Optional[str] = None
    mjml_source_url: Optional[str] = None
    clarification_questions: Optional[list[str]] = None
    brief_submission_token: Optional[str] = Field(
        default=None,
        description="Token to be used for submitting an amended brief, if required.",
    )
    message: Optional[str] = Field(
        default=None,
        description="A descriptive message about the current status or any errors.",
    )
    # Fields related to MJML generation and validation
    current_mjml: Optional[str] = Field(
        default=None,
        description="The most recent MJML source generated by the graph, if available.",
    )
    compiled_html: Optional[str] = Field(
        default=None,
        description="The most recent compiled HTML from the graph, if available.",
    )
    mjml_validation_status: Optional[str] = Field(
        default=None,
        description="The validation status of the current_mjml (e.g., VALID, INVALID, NOT_ATTEMPTED).",
    )
    # Sprint 3: Add field for approved version ID
    approved_version_id: Optional[str] = Field(
        default=None,
        description="The ID of the version that has been formally approved, if any.",
    )


class AmendedBriefRequest(BaseModel):
    """
    Schema for submitting an amended brief when clarification was requested.
    """

    user_brief: UserBriefSchema = Field(
        ..., description="The amended user brief content."
    )
    brief_token: Optional[str] = Field(
        default=None,
        description="Optional token to validate/track the amended brief submission, potentially provided in the status response that indicated clarification was needed.",
    )


# --- Schemas for Template Versioning (Sprint 2) ---


class TemplateVersionBase(BaseModel):
    """
    Base schema for a template version, containing common fields.
    """

    template_id: str = Field(
        description="Identifier for the parent template (e.g., graph execution ID)."
    )
    version_id: str = Field(
        description="Unique identifier for this specific version of the template."
    )
    mjml_source: str = Field(description="The MJML source code for this version.")
    compiled_html: str = Field(description="The compiled HTML from the MJML source.")
    user_brief_snapshot: Optional[dict] = Field(
        default=None,
        description="A snapshot of the user brief that led to this version.",
    )
    image_assets: Optional[dict] = Field(
        default=None,
        description="Information about image assets used in this version (e.g., URLs, prompts).",
    )
    change_trigger: Optional[dict] = Field(
        default=None,
        description="Information about what triggered the creation of this version (e.g., initial generation, feedback round).",
    )
    is_approved: bool = Field(
        default=False,
        description="Indicates if this version has been approved by the user.",
    )


class TemplateVersionCreate(TemplateVersionBase):
    """
    Schema for creating a new template version.
    Inherits all fields from TemplateVersionBase.
    `created_at` will be set by the database.
    """

    pass


class TemplateVersionResponse(TemplateVersionBase):
    """
    Schema for representing a template version in API responses.
    Includes all base fields plus database-generated fields like `created_at`.
    """

    created_at: datetime = Field(
        description="Timestamp of when this version was created."
    )

    model_config = {"from_attributes": True}  # Pydantic V2 way to enable ORM mode


# --- Schemas for Listing Template Version Metadata ---


class VersionPreviewURLsSchema(BaseModel):
    html: str
    mjml: str


class VersionMetadataSchema(BaseModel):
    version_id: str
    created_at: datetime
    change_trigger: Optional[Dict[str, Any]] = None
    is_approved: bool = False  # Default to False as in DB model
    preview_urls: VersionPreviewURLsSchema


class TemplateVersionListSchema(BaseModel):
    versions: List[VersionMetadataSchema]


# --- Schemas for Feedback (Sprint 3) ---


class FeedbackRequestSchema(BaseModel):
    """
    Schema for submitting feedback on a template version.
    """

    feedback_text: str = Field(
        ...,
        min_length=1,
        description="The textual feedback provided by the user for the template version.",
    )


# --- Schemas for Approval (Sprint 3) ---


class ApprovalResponseSchema(BaseModel):
    """
    Schema for the response when a template version is successfully approved.
    """

    template_id: str = Field(
        ..., description="The ID of the template whose version was approved."
    )
    approved_version_id: str = Field(
        ..., description="The ID of the version that was approved."
    )
    status: str = Field(
        default="approved_pending_import",
        description="The new status of the template after approval.",
    )
    message: str = Field(
        default="Template version approved successfully. Pending import to Beefree.",
        description="Confirmation message.",
    )
