"""create_template_versions_table

Revision ID: c1e1c3e07a5e
Revises:
Create Date: 2025-05-30 14:48:51.701933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1e1c3e07a5e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template_versions",
        sa.Column("template_id", sa.Text(), nullable=False),
        sa.Column("version_id", sa.Text(), nullable=False),
        sa.Column("mjml_source", sa.Text(), nullable=False),
        sa.Column("compiled_html", sa.Text(), nullable=False),
        sa.Column(
            "user_brief_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "image_assets", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "change_trigger", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("template_id", "version_id"),
    )
    op.create_index(
        op.f("ix_template_versions_template_id"),
        "template_versions",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_versions_version_id"),
        "template_versions",
        ["version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_template_versions_version_id"), table_name="template_versions"
    )
    op.drop_index(
        op.f("ix_template_versions_template_id"), table_name="template_versions"
    )
    op.drop_table("template_versions")
    # ### end Alembic commands ###
