from dotenv import load_dotenv

load_dotenv()

from typing import Optional, Dict, Any, List

from pydantic import BaseModel, Field


class GraphState(BaseModel):
    """
    Represents the overall state of the template generation graph.
    This state is passed between nodes in the LangGraph execution.
    """

    # Initial input
    user_brief_data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="The initial user brief for the template, stored as a dictionary.",
    )

    # --- RAG Workflow Fields (Sprint 5) ---
    rag_flow: bool = Field(
        default=False,
        description="Flag to indicate if the RAG workflow is being used.",
    )
    use_placeholders: bool = Field(
        default=True,
        description="If true, use placeholder media; if false, use original media.",
    )
    plain_text_brief: Optional[str] = Field(
        default=None,
        description="The unstructured, plain text brief used as input for the RAG flow.",
    )
    brief_fingerprint: Optional[str] = Field(
        default=None,
        description="The structural fingerprint generated from the plain text brief.",
    )
    brief_embedding: Optional[List[float]] = Field(
        default=None,
        description="The vector embedding generated from the brief's fingerprint.",
    )
    retrieved_template_html: Optional[str] = Field(
        default=None,
        description="The raw HTML of the best matching template retrieved from the corpus.",
    )
    final_html_content: Optional[str] = Field(
        default=None,
        description="The final, populated HTML content generated by the RAG workflow.",
    )

    # For clarification loop
    clarification_questions: Optional[list[str]] = Field(
        default=None,
        description="Questions generated by the brief analyzer for the user.",
    )
    amended_brief_data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="The amended brief provided by the user after clarification, stored as a dictionary.",
    )
    clarification_rounds_count: int = Field(
        default=0,
        description="Number of clarification rounds that have been completed. Used to limit clarifications to one round.",
    )

    # MJML generation related
    current_mjml: Optional[str] = Field(
        default=None, description="The currently generated or revised MJML content."
    )
    compiled_html: Optional[str] = Field(
        default=None, description="The HTML compiled from the current MJML."
    )
    mjml_validation_status: Optional[str] = Field(
        default=None,
        description="Status of MJML validation (e.g., VALID, INVALID, NOT_AVAILABLE, ERROR).",
    )

    # Image generation related (Sprint 2)
    image_prompts: Optional[list[str]] = Field(
        default=None,
        description="List of textual prompts for image generation, derived from the brief.",
    )
    generated_image_urls: Optional[list[str]] = Field(
        default=None,
        description="List of URLs for images generated by the image generation service.",
    )
    image_urls_map: Optional[Dict[str, Optional[str]]] = Field(
        default_factory=dict,
        description="Mapping of original image prompts to their generated URLs (or None if failed).",
    )

    # Error and status tracking
    error_message: Optional[str] = Field(
        default=None, description="Any error message encountered during a step."
    )
    last_operation_status: Optional[str] = Field(
        default=None,
        description="Status of the last performed operation (e.g., 'success', 'failure').",
    )

    # Versioning related (Sprint 2)
    stored_version_info: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Information about the last version stored in TemplateStoreDB.",
    )
    current_version_id_stored: Optional[str] = Field(
        default=None,
        description="The version_id of the template last successfully stored in TemplateStoreDB.",
    )

    # --- Fields for Feedback and Revision Loop (Sprint 3) ---
    user_feedback_content: Optional[str] = Field(
        default=None,
        description="The feedback content submitted by the user for a specific version.",
    )
    version_id_for_feedback: Optional[str] = Field(
        default=None,
        description="The ID of the template version for which feedback was submitted.",
    )
    revised_mjml_candidate: Optional[str] = Field(
        default=None,
        description="The revised MJML content generated by the feedback engine, pending validation.",
    )

    is_test_forcing_brief_ok: Optional[bool] = Field(
        default=False, description="FOR TESTING ONLY: Force brief_ok status."
    )  # Temporary for testing

    # To manage retries or specific flow control if needed
    # retry_count: int = 0

    # For storing intermediate data or outputs from various nodes if not directly part of the main flow items
    # intermediate_data: Dict[str, Any] = Field(default_factory=dict)

    # Configuration or context that might need to be passed through the graph
    # config: Optional[Dict[str, Any]] = None # e.g., API keys if not handled globally

    class Config:
        # Pydantic V2 config
        arbitrary_types_allowed = (
            True  # Useful for LangGraph if complex types are ever added
        )


# Example of how you might use it:
# initial_state = GraphState(user_brief=UserBriefSchema(...))
# current_state.clarification_questions = ["What is X?"]
